easy_admin:
    entities:
        # List the entity class name you want to manage
        Contacter:
          class: App\Entity\Contacter
        Profil:
          class: App\Entity\Profil
          disabled_actions: ['new', 'edit']
          list:
            fields:
              - 'id'
              - 'username'
              - 'lastname'
              - 'mail'
              - {property: 'licence.numLicence', label: 'Numéro de licence'}
        Licence:
          class: App\Entity\Licence
          form:
            fields:
              - 'lastname'
              - 'firstname'
              - 'numLicence'
        Events:
          class: App\Entity\Events
        Newsletter:
          class: App\Entity\Newsletter